# Generated by Django 4.2.14 on 2024-07-15 03:48

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='MailingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mailing')),
            ],
        ),
    ]
