# Generated by Django 4.2.14 on 2024-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_batch_name_alter_mailingtoken_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
