# Generated by Django 4.2.15 on 2024-08-14 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_batch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
