# Generated by Django 4.2.14 on 2024-07-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_alter_batch_name_alter_mailingtoken_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('seen', models.BooleanField(default=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mailing')),
            ],
        ),
    ]
