# Generated by Django 4.2.14 on 2024-07-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_batch_name'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailseen',
            options={'verbose_name': 'Mail Seen', 'verbose_name_plural': 'Mail Seen'},
        ),
        migrations.RemoveField(
            model_name='mailseen',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='mailseen',
            name='seen',
        ),
        migrations.AddField(
            model_name='mailseen',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mailseen',
            name='mailing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_seen', to='home.mailing'),
        ),
    ]
