# Generated by Django 4.2.14 on 2024-07-27 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_mailseen_options_remove_mailseen_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailseen',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
